services:
  # PostgreSQL service
  postgres:
    image: postgres:15
    container_name: cxxc_db
    restart: always
    environment:
      POSTGRES_USER: cxxc
      POSTGRES_PASSWORD: 6jie8yO8nt85
      POSTGRES_DB: cxxc
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql@15/data

  # MinIO service (S3-compatible storage)
  minio:
    image: quay.io/minio/minio
    container_name: cxxc_files
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: cxxc
      MINIO_ROOT_PASSWORD: JdbP9QQs77w5
    volumes:
      - minio_data:/data

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq
    container_name: cxxc_queue
    restart: always
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: cxxc
      RABBITMQ_DEFAULT_PASS: qAxg6mB0x8Jw

volumes:
  pg_data:
  minio_data:
