services:
  # PostgreSQL service
  postgres:
    image: postgres:15
    container_name: cxxc_db
    restart: always
    environment:
      POSTGRES_USER: cxxc
      POSTGRES_PASSWORD: 6jie8yO8nt85
      POSTGRES_DB: cxxc
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # MinIO service (S3-compatible storage)
  minio:
    image: quay.io/minio/minio
    container_name: cxxc_files
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: cxxc
      MINIO_ROOT_PASSWORD: JdbP9QQs77w5
    volumes:
      - minio_data:/data

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq
    container_name: cxxc_queue
    restart: always
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: cxxc
      RABBITMQ_DEFAULT_PASS: qAxg6mB0x8Jw

  # NestJS App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio
      - rabbitmq
    environment:
      # PostgreSQL
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: cxxc
      DB_PASSWORD: 6jie8yO8nt85
      DB_DATABASE: cxxc
      
      # MinIO
      MINIO_ENDPOINT: http://file.cxxc.vn
      MINIO_ACCESS_KEY: cxxc
      MINIO_SECRET_KEY: JdbP9QQs77w5

      # RabbitMQ
      RABBITMQ_URI: amqp://cxxc:qAxg6mB0x8Jw@rabbitmq:5672

      # Firebase
      GOOGLE_APPLICATION_CREDENTIALS: /usr/src/app/cxxc-94c22-firebase-adminsdk-uf6vp-21626b7d43.json
    volumes:
      # - .:/usr/src/app:cached
      - /usr/src/app/node_modules
      - ./cxxc-94c22-firebase-adminsdk-uf6vp-21626b7d43.json:/usr/src/app/cxxc-94c22-firebase-adminsdk-uf6vp-21626b7d43.json

volumes:
  pg_data:
  minio_data:
