version: '3.8'
services:
  # MySQL database service
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cxxc@123
      MYSQL_DATABASE: cxxc
      MYSQL_USER: cxxc
      MYSQL_PASSWORD: cxxc@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # NestJS service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: nestdb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql_data:
