services:
  # NestJS App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cxxc_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      # PostgreSQL
      DB_HOST: 183.81.33.204
      DB_PORT: 5432
      DB_USERNAME: cxxc
      DB_PASSWORD: 6jie8yO8nt85
      DB_DATABASE: cxxc
      SECRET: CXXC321
      
      # MinIO
      MINIO_ENDPOINT: https://file.cxxc.vn
      MINIO_ACCESS_KEY: cxxc
      MINIO_SECRET_KEY: xz7WkmlpLsIwaUfzR38se1dJzSNg3wITXDYRJmVj

      # RabbitMQ
      RABBITMQ_URI: amqp://cxxc:qAxg6mB0x8Jw@rabbitmq:5672

      # Firebase
      GOOGLE_APPLICATION_CREDENTIALS: /usr/src/app/cxxc-94c22-firebase-adminsdk-uf6vp-21626b7d43.json
    volumes:
      # - .:/usr/src/app:cached
      - /usr/src/app/node_modules
      - ./cxxc-94c22-firebase-adminsdk-uf6vp-21626b7d43.json:/usr/src/app/cxxc-94c22-firebase-adminsdk-uf6vp-21626b7d43.json
    networks:
      - cxxc_net

networks:
  cxxc_net:
