version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres:14
    container_name: cxxc_db
    restart: always
    environment:
      POSTGRES_USER: cxxc
      POSTGRES_PASSWORD: cxxc123
      POSTGRES_DB: cxxc
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # MinIO service (S3-compatible storage)
  minio:
    image: minio/minio
    container_name: cxxc_files
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: cxxc
      MINIO_ROOT_PASSWORD: cxxc123
    volumes:
      - minio_data:/data

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cxxc_queue
    restart: always
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: cxxc
      RABBITMQ_DEFAULT_PASS: cxxc123

  # NestJS App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio
      - rabbitmq
    environment:
      # PostgreSQL
      DB_HOST: cxxc_db
      DB_PORT: 5432
      DB_USERNAME: cxxc
      DB_PASSWORD: cxxc123
      DB_DATABASE: cxxc
      
      # MinIO
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: cxxc
      MINIO_SECRET_KEY: cxxc123

      # RabbitMQ
      RABBITMQ_URI: amqp://cxxc:cxxc123@rabbitmq:5672
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pg_data:
  minio_data:
