name: Deploy to Server

on:
  push:
    branches:
      - main  # hoặc branch bạn muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy over SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ${{ secrets.APP_DIR }}
          git pull origin main
          docker compose -f docker-compose.yml -f docker-compose.app.yml down
          docker compose -f docker-compose.yml -f docker-compose.app.yml up -d --build
        EOF
